name: Build on Push

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BACKEND_URL: 'http://localhost:8000'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change to the correct directory
        run: cd backend

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Wait for server to be ready
        run: |
          while ! curl -s http://localhost:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done

      - name: Verify server is running
        run: curl http://localhost:8000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: Install Backend Dependencies
        run: yarn install
        working-directory: ./backend

      - name: Run Prisma Migrate
        env:
          DATABASE_URL: mysql://root:password@127.0.0.1:3306/db
        run: yarn --cwd backend prisma migrate deploy

      - name: Build Backend
        run: yarn build
        working-directory: ./backend

      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build Frontend
        run: yarn build
        working-directory: ./frontend
