name: Format and Build

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BACKEND_URL: 'https://api.engineer-master.net'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: Yarn Installation
        run: yarn

      - name: Format with Lint
        run: yarn eslint --fix .

      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build Frontend
        run: yarn build
        working-directory: ./frontend

      - name: Install Backend Dependencies
        run: yarn install
        working-directory: ./backend

      - name: Build Backend
        run: yarn build
        working-directory: ./backend
